llsfrb:
  mps:
    enable: true
    stations:
      C-BS:
        active: true
        #host: 192.169.0.100
        host: localhost
        port: !tcp-port 4840
        type: BS
        connection: mockup
      C-CS1:
        active: true
        host: localhost
        port: !tcp-port 4840
        type: CS
        connection: mockup
      C-CS2:
        active: true
        host: localhost
        port: !tcp-port 4842
        type: CS
        connection: mockup
      C-RS1:
        active: true
        host: localhost
        port: !tcp-port 4843
        type: RS
        connection: mockup
      C-RS2:
        active: true
        host: localhost
        port: !tcp-port 4844
        type: RS
        connection: mockup
      C-DS:
        active: true
        host: localhost
        port: !tcp-port 4845
        type: DS
        connection: mockup
      C-SS:
        active: true
        host: localhost
        port: !tcp-port 4846
        type: SS
        connection: mockup
      M-BS:
        active: true
        host: 192.169.0.100
        port: !tcp-port 4840
        type: BS
        connection: mockup
      M-CS1:
        active: true
        host: 192.168.0.1
        port: !tcp-port 4840
        type: CS
        connection: mockup
        #connection: plc
      M-CS2:
        active: true
        host: 192.169.0.100
        port: !tcp-port 4842
        type: CS
        connection: mockup
      M-RS1:
        active: true
        host: 192.169.0.100
        port: !tcp-port 4843
        type: RS
        connection: mockup
      M-RS2:
        active: true
        host: 192.169.0.100
        port: !tcp-port 4844
        type: RS
        connection: mockup
      M-DS:
        active: true
        host: 192.169.0.100
        port: !tcp-port 4845
        type: DS
        connection: mockup
      M-SS:
        active: true
        host: 192.169.0.100
        port: !tcp-port 4846
        type: SS
        connection: mockup
