%YAML 1.2
---
---
# Default settings, where all machines use plc connection

llsfrb:
  mps:
    enable: true
    stations:
      C-BS:
        active: true
        type: BS
        host: broker
        port: !tcp-port 1883
        connection: mqtt
      C-CS1:
        active: true
        host: broker
        port: !tcp-port 1883
        type: CS
        connection: mqtt
      C-CS2:
        active: true
        host: broker
        port: !tcp-port 1883
        type: CS
        connection: mqtt
      C-RS1:
        active: true
        host: broker
        port: !tcp-port 1883
        type: RS
        connection: mqtt
      C-RS2:
        active: true
        host: broker
        port: !tcp-port 1883
        type: RS
        connection: mqtt
      C-DS:
        active: true
        host: broker
        port: !tcp-port 1883
        type: DS
        connection: mqtt
      C-SS:
        active: true
        host: broker
        port: !tcp-port 4846
        type: SS
        connection: mockup
      M-BS:
        active: true
        host: broker
        port: !tcp-port 4850
        type: BS
        connection: mockup
      M-CS1:
        active: true
        host: broker
        port: !tcp-port 4851
        type: CS
        connection: mockup
      M-CS2:
        active: true
        host: broker
        port: !tcp-port 4852
        type: CS
        connection: mockup
      M-RS1:
        active: true
        host: broker
        port: !tcp-port 4853
        type: RS
        connection: mockup
      M-RS2:
        active: true
        host: broker
        port: !tcp-port 4854
        type: RS
        connection: mockup
      M-DS:
        active: true
        host: broker
        port: !tcp-port 4855
        type: DS
        connection: mockup
      M-SS:
        active: true
        host: broker
        port: !tcp-port 4840
        type: SS
        connection: mockup
